org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.network.timeout=600000
systemProp.http.connectionTimeout=600000
systemProp.http.socketTimeout=600000
systemProp.https.connectionTimeout=600000
systemProp.https.socketTimeout=600000
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=true
